image:
  repository: ghcr.io/ibra86/k8s-controller-patterns
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

args:
  - server
  - --log-level
  - debug

service:
  type: ClusterIP
  port: 80
  targetPort: 8080